export const videos = [
  {
    "phase": "Menstrual (bleeding)",
    "energy": "Low",
    "intent": "Rest & soothe (cramps, low back, nervous system)",
    "title": "Quick Restorative Yin Yoga – 20 Minute Practice",
    "channel": "Yoga With Adriene",
    "length": "≈20 min",
    "language": "EN",
    "style": "Restorative / Yin",
    "breathFocus": "High",
    "modifications": "Yes (props-friendly)",
    "notes": "Restorative pacing; great when you want minimal effort and maximum downshift.",
    "url": "https://www.youtube.com/watch?v=nylNjxeOeSw"
  },
  {
    "phase": "Menstrual (bleeding)",
    "energy": "Low",
    "intent": "Rest & soothe (PMS + cramps)",
    "title": "Yoga for Cramps and PMS | 20-Minute Home Yoga",
    "channel": "Yoga With Adriene",
    "length": "≈20 min",
    "language": "EN",
    "style": "Gentle / Restorative",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Designed for PMS/cramps; soft belly breathing cues.",
    "url": "https://www.youtube.com/watch?v=4JaCcp39iVI"
  },
  {
    "phase": "Menstrual (bleeding)",
    "energy": "Low",
    "intent": "Rest & soothe (stress relief)",
    "title": "20 minute Yin Yoga for Relaxation (Release Stress & CALM)",
    "channel": "SarahBethYoga",
    "length": "20 min",
    "language": "EN",
    "style": "Yin / Relaxation",
    "breathFocus": "High",
    "modifications": "Yes (all levels)",
    "notes": "Simple, calming shapes with longer holds; easy to modify.",
    "url": "https://www.youtube.com/watch?v=AFCRhcXYFm4"
  },
  {
    "phase": "Menstrual (bleeding)",
    "energy": "Low",
    "intent": "Rest & soothe (period support in Spanish)",
    "title": "YOGA para la MENSTRUACIÓN – alivia dolores, hinchazón y SPM (20 min)",
    "channel": "Boticaria Yoga",
    "length": "20 min",
    "language": "ES",
    "style": "Suave / Restaurativo",
    "breathFocus": "High",
    "modifications": "Yes (all levels)",
    "notes": "Period-focused; gentle/restorative approach with relaxation emphasis.",
    "url": "https://www.youtube.com/watch?v=WfIWo3eGtsE"
  },
  {
    "phase": "Menstrual (bleeding)",
    "energy": "Low",
    "intent": "Rest & soothe (tender heart)",
    "title": "Yoga for Heavy Hearts",
    "channel": "Yoga With Adriene",
    "length": "18:56",
    "language": "EN",
    "style": "Gentle / seated",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Mostly seated, slow, nothing-to-fix practice; very low effort — rest days.",
    "url": "https://www.youtube.com/watch?v=2akHh5GgzvM"
  },
  {
    "phase": "Menstrual (bleeding)",
    "energy": "Low",
    "intent": "Rest & soothe (listening & rest)",
    "title": "Return - 3 - Listen",
    "channel": "Yoga With Adriene",
    "length": "25:43",
    "language": "EN",
    "style": "Gentle / body scan",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Body scan, soft spinal work, optional bolster rest; inward self-assessment fits the bleed.",
    "url": "https://www.youtube.com/watch?v=ViLAjVstszQ"
  },
  {
    "phase": "Menstrual (bleeding)",
    "energy": "Low",
    "intent": "Rest & soothe (unwind)",
    "title": "Anytime Unwind | Full Yoga Practice",
    "channel": "Yoga With Adriene",
    "length": "23:02",
    "language": "EN",
    "style": "Slow / unwind (props)",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Slow, soft, block + blanket, unravels tension — minimal-effort rest practice.",
    "url": "https://www.youtube.com/watch?v=s7ryIG-GQr8"
  },
  {
    "phase": "Menstrual (bleeding)",
    "energy": "Low",
    "intent": "Rest & soothe (reset)",
    "title": "New Moon Yoga",
    "channel": "Yoga With Adriene",
    "length": "23:10",
    "language": "EN",
    "style": "Hatha + breath + meditation",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "New-moon reset with check-in and self-care; grounding and reflective.",
    "url": "https://www.youtube.com/watch?v=71PmTZOgmXA"
  },
  {
    "phase": "Menstrual (bleeding)",
    "energy": "Low",
    "intent": "Rest & soothe (rest & heal)",
    "title": "Yoga For Sick Recovery",
    "channel": "Yoga With Adriene",
    "length": "21:17",
    "language": "EN",
    "style": "Gentle / recovery",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Surrender to rest and recovery; gentle and healing — low-energy days.",
    "url": "https://www.youtube.com/watch?v=hDFHCHRcd1I"
  },
  {
    "phase": "Menstrual (bleeding)",
    "energy": "Low",
    "intent": "Rest & soothe (process & reflect)",
    "title": "Brain + Body Balance | 22-minute Yoga Practice",
    "channel": "Yoga With Adriene",
    "length": "22:38",
    "language": "EN",
    "style": "Holistic balance",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Ritual for processing, healing and reflection — menstrual self-evaluation.",
    "url": "https://www.youtube.com/watch?v=XN3JB67-a_k"
  },
  {
    "phase": "Menstrual (bleeding)",
    "energy": "Low",
    "intent": "Rest & soothe (cozy)",
    "title": "Gentle, Relaxing, Cozy Flow | 20-Minute Home Yoga",
    "channel": "Yoga With Adriene",
    "length": "21:10",
    "language": "EN",
    "style": "Gentle floor flow",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Easy floor practice with blanket and pillow, pajamas welcome, ending in calm breathing — rest-day yoga.",
    "url": "https://www.youtube.com/watch?v=jHZPtn15agE"
  },
  {
    "phase": "Menstrual (bleeding)",
    "energy": "Low",
    "intent": "Rest & soothe (chronic pain)",
    "title": "Yoga For Chronic Pain | 25-Minute Yoga",
    "channel": "Yoga With Adriene",
    "length": "25:34",
    "language": "EN",
    "style": "Gentle (mat or chair)",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Gentle practice you can do in a chair, built around pain and healing — lowest-effort days.",
    "url": "https://www.youtube.com/watch?v=BFaXfQpxnps"
  },
  {
    "phase": "Menstrual (bleeding)",
    "energy": "Low",
    "intent": "Rest & soothe (surrender)",
    "title": "Yoga For Suffering | 20-Minute Yoga Flow",
    "channel": "Yoga With Adriene",
    "length": "20:33",
    "language": "EN",
    "style": "Gentle flow",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Gentle, set-down-your-burdens practice; commenters found it cathartic — low effort.",
    "url": "https://www.youtube.com/watch?v=reASzZP63HQ"
  },
  {
    "phase": "Menstrual (bleeding)",
    "energy": "Low",
    "intent": "Rest & soothe (breath & calm)",
    "title": "Pranayama Potion | 20-Minute Yoga Practice",
    "channel": "Yoga With Adriene",
    "length": "21:23",
    "language": "EN",
    "style": "Pranayama (chair OK)",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Calming breath-ratio practice that can be done in a chair — very low effort.",
    "url": "https://www.youtube.com/watch?v=4uNdlGcySLQ"
  },
  {
    "phase": "Menstrual (bleeding)",
    "energy": "Low",
    "intent": "Rest & soothe (reboot)",
    "title": "Yoga For Travel",
    "channel": "Yoga With Adriene",
    "length": "23:51",
    "language": "EN",
    "style": "Slow balancing flow",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "For after a long trip or a tiring day; commenters describe it as quiet and slow — low effort.",
    "url": "https://www.youtube.com/watch?v=C0U7v4iCemM"
  },
  {
    "phase": "Menstrual (bleeding)",
    "energy": "Low",
    "intent": "Rest & soothe (low-back release)",
    "title": "Yoga For Hips & Lower Back Release",
    "channel": "Yoga With Adriene",
    "length": "23:20",
    "language": "EN",
    "style": "Gentle hips + low back",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Inward, sigh-it-out release for hips and lower back — low-back ache is a named menstrual symptom.",
    "url": "https://www.youtube.com/watch?v=Ho9em79_0qg"
  },
  {
    "phase": "Menstrual (bleeding)",
    "energy": "Low",
    "intent": "Rest & soothe (restore)",
    "title": "Yoga For Manual Labor",
    "channel": "Yoga With Adriene",
    "length": "23:03",
    "language": "EN",
    "style": "Restorative",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "A restorative wind-down that calms the nervous system — rest days.",
    "url": "https://www.youtube.com/watch?v=juyN0Y7F5Ug"
  },
  {
    "phase": "Menstrual (bleeding)",
    "energy": "Low",
    "intent": "Rest & soothe (soothe)",
    "title": "Yoga For Loneliness",
    "channel": "Yoga With Adriene",
    "length": "20:43",
    "language": "EN",
    "style": "Low, hands-free flow",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Low to the ground, off the knees, soothing with a touch of core — low effort.",
    "url": "https://www.youtube.com/watch?v=DFVzpvz0FgQ"
  },
  {
    "phase": "Menstrual (bleeding)",
    "energy": "Low",
    "intent": "Rest & soothe (rainy day)",
    "title": "Yoga For a Rainy Day",
    "channel": "Yoga With Adriene",
    "length": "23:08",
    "language": "EN",
    "style": "Low, relaxing stretch",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Relaxing low-to-the-ground stretch, pajamas encouraged; commenters use it on 'just don't wanna' days.",
    "url": "https://www.youtube.com/watch?v=1y-3pGVVQkE"
  },
  {
    "phase": "Menstrual (bleeding)",
    "energy": "Low",
    "intent": "Rest & soothe (a little goes a long way)",
    "title": "Yoga For Beginners - A Little Goes a Long Way",
    "channel": "Yoga With Adriene",
    "length": "19:29",
    "language": "EN",
    "style": "Gentle + breathwork",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "The 'ultimate gentle' home practice mixing breath and simple poses — low effort.",
    "url": "https://www.youtube.com/watch?v=M7JfqOfqSmI"
  },
  {
    "phase": "Menstrual (bleeding)",
    "energy": "Low",
    "intent": "Rest & soothe (bedtime)",
    "title": "Bedtime Yoga | 20 Minute Bedtime Yoga Practice",
    "channel": "Yoga With Adriene",
    "length": "19:09",
    "language": "EN",
    "style": "Gentle bedtime",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Gentle evening practice to decompress from stress and tension before sleep — low effort.",
    "url": "https://www.youtube.com/watch?v=v7SN-d4qXx0"
  },
  {
    "phase": "Menstrual (bleeding)",
    "energy": "Low",
    "intent": "Rest & soothe (broken heart)",
    "title": "Yoga For a Broken Heart - Unconditional Love",
    "channel": "Yoga With Adriene",
    "length": "23:19",
    "language": "EN",
    "style": "Nurturing heart flow",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Nourishing practice for grief and a heavy heart — low effort, tender days.",
    "url": "https://www.youtube.com/watch?v=u8sC_bhpCYQ"
  },
  {
    "phase": "Menstrual (bleeding)",
    "energy": "Low",
    "intent": "Rest & soothe (sick days)",
    "title": "Yoga For When You Are SICK",
    "channel": "Yoga With Adriene",
    "length": "20:07",
    "language": "EN",
    "style": "Gentle restorative",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Gentle restorative practice for when you're sick — lowest effort.",
    "url": "https://www.youtube.com/watch?v=n5YvtYXSocw"
  },
  {
    "phase": "Early follicular (post-bleed)",
    "energy": "Low → Moderate",
    "intent": "Rebuild & mobilize (gentle wake-up)",
    "title": "Sunrise Yoga | 15 Min Morning Yoga Practice",
    "channel": "Yoga With Tim",
    "length": "15 min",
    "language": "EN",
    "style": "Morning flow",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "A clean, cue-forward wake-up flow—great for easing back into movement.",
    "url": "https://www.youtube.com/watch?v=lsV286HgxPU"
  },
  {
    "phase": "Early follicular (post-bleed)",
    "energy": "Low → Moderate",
    "intent": "Rebuild & mobilize (sweet release)",
    "title": "15 min Morning Yoga for Flexibility – Sweet Release SLOW FLOW",
    "channel": "Yoga with Kassandra",
    "length": "15 min",
    "language": "EN",
    "style": "Slow flow",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Slow-flow pacing with clear cueing; good for stiffness and gradual ramp-up.",
    "url": "https://www.youtube.com/watch?v=zLer5A9LgMs"
  },
  {
    "phase": "Early follicular (post-bleed)",
    "energy": "Low → Moderate",
    "intent": "Rebuild & mobilize (stress + flexibility)",
    "title": "Yoga to Heal Stress – 20 Minute Yoga Practice (Flexibility & Relaxation)",
    "channel": "Yoga With Adriene",
    "length": "≈20 min",
    "language": "EN",
    "style": "Gentle flow",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Breath-led, down-regulating practice with plenty of room to soften.",
    "url": "https://www.youtube.com/watch?v=tD_l3fDTFyg"
  },
  {
    "phase": "Early follicular (post-bleed)",
    "energy": "Low → Moderate",
    "intent": "Rebuild & mobilize (full body, Spanish)",
    "title": "Yoga at Home – Full Body Class | Vinyasa Yoga (20 min)",
    "channel": "MalovaElena",
    "length": "20 min",
    "language": "ES",
    "style": "Vinyasa",
    "breathFocus": "Med–High",
    "modifications": "Some options",
    "notes": "Spanish vinyasa with an alignment-forward approach (great for language + form).",
    "url": "https://www.youtube.com/watch?v=69G2udeeXPc"
  },
  {
    "phase": "Early follicular (post-bleed)",
    "energy": "Low → Moderate",
    "intent": "Rebuild & mobilize (begin again)",
    "title": "Early Morning Yoga and Meditation - 20 Minute Yoga Practice",
    "channel": "Yoga With Adriene",
    "length": "20:20",
    "language": "EN",
    "style": "Gentle morning + meditation",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Gentle wake-up with meditation, explicitly about beginning again — easing back in.",
    "url": "https://www.youtube.com/watch?v=mMSsHji8LDA"
  },
  {
    "phase": "Early follicular (post-bleed)",
    "energy": "Low → Moderate",
    "intent": "Rebuild & mobilize (gentle rebuild)",
    "title": "Prana - Day 5",
    "channel": "Yoga With Adriene",
    "length": "19:13",
    "language": "EN",
    "style": "Therapeutic + light strength",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Light strength (forearm plank) balanced with surrender poses; described as therapeutic and fun.",
    "url": "https://www.youtube.com/watch?v=p0KSFLf_XJA"
  },
  {
    "phase": "Early follicular (post-bleed)",
    "energy": "Low → Moderate",
    "intent": "Rebuild & mobilize (low mood → light)",
    "title": "Yoga For Seasonal Affective Disorder",
    "channel": "Yoga With Adriene",
    "length": "25:26",
    "language": "EN",
    "style": "Tender flow",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Moves from heaviness toward sparking energy — rebuilding after a low stretch.",
    "url": "https://www.youtube.com/watch?v=pNpEWvIGFIA"
  },
  {
    "phase": "Early follicular (post-bleed)",
    "energy": "Low → Moderate",
    "intent": "Rebuild & mobilize (wake up & stretch)",
    "title": "Morning Mobility Yoga | Wake Up and Stretch!",
    "channel": "Yoga With Adriene",
    "length": "22:22",
    "language": "EN",
    "style": "Morning mobility",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Repeatable morning range-of-motion practice — gentle ramp back into movement.",
    "url": "https://www.youtube.com/watch?v=2IcWJobNDck"
  },
  {
    "phase": "Early follicular (post-bleed)",
    "energy": "Low → Moderate",
    "intent": "Rebuild & mobilize (intro to flow)",
    "title": "Yoga Flow For Beginners | Intro To Flow",
    "channel": "Yoga With Adriene",
    "length": "24:53",
    "language": "EN",
    "style": "Slow flow (beginner)",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Slow, mindful beginner flow that balances the nervous system — easing back in.",
    "url": "https://www.youtube.com/watch?v=4TLHLNX65-4"
  },
  {
    "phase": "Early follicular (post-bleed)",
    "energy": "Low → Moderate",
    "intent": "Rebuild & mobilize (low motivation)",
    "title": "Yoga For When You Are Feeling Unmotivated | 20-Minute Home Yoga",
    "channel": "Yoga With Adriene",
    "length": "22:40",
    "language": "EN",
    "style": "Build-up flow",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Starts on empty (side-lying) and builds to warriors — exactly the post-bleed ramp.",
    "url": "https://www.youtube.com/watch?v=C1pm0g2mSlE"
  },
  {
    "phase": "Early follicular (post-bleed)",
    "energy": "Low → Moderate",
    "intent": "Rebuild & mobilize (start here)",
    "title": "20-Minute Yoga For Beginners | Start Yoga Here...",
    "channel": "Yoga With Adriene",
    "length": "21:41",
    "language": "EN",
    "style": "Beginner foundations",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Meditative-paced foundations for spine, hips, core — ideal ramp back in.",
    "url": "https://www.youtube.com/watch?v=vNyJuQuuMC8"
  },
  {
    "phase": "Early follicular (post-bleed)",
    "energy": "Low → Moderate",
    "intent": "Rebuild & mobilize (transitions)",
    "title": "Yoga For Transitions | 20-Minute Home Yoga",
    "channel": "Yoga With Adriene",
    "length": "22:58",
    "language": "EN",
    "style": "Hip + core flow",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Deep hip openers, low-back relief and some core (plus an optional side crow) framed around moving through change — easing out of the bleed.",
    "url": "https://www.youtube.com/watch?v=AQuSHVoSLc8"
  },
  {
    "phase": "Early follicular (post-bleed)",
    "energy": "Low → Moderate",
    "intent": "Rebuild & mobilize (rebirth)",
    "title": "Rebirth Yoga | 24-Minute Yoga Flow",
    "channel": "Yoga With Adriene",
    "length": "24:02",
    "language": "EN",
    "style": "Renewal flow",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Renewal and 'letting things cycle through', building gentle heat and strength — a fitting restart after the bleed.",
    "url": "https://www.youtube.com/watch?v=M8gN00LgJto"
  },
  {
    "phase": "Early follicular (post-bleed)",
    "energy": "Low → Moderate",
    "intent": "Rebuild & mobilize (low energy)",
    "title": "Fill Your Cup Yoga | 20-Minute Home Yoga",
    "channel": "Yoga With Adriene",
    "length": "20:57",
    "language": "EN",
    "style": "Breath + body check-in",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Explicitly for low-energy days when you still want to do something — the post-bleed ramp.",
    "url": "https://www.youtube.com/watch?v=H4dVbaLqg84"
  },
  {
    "phase": "Early follicular (post-bleed)",
    "energy": "Low → Moderate",
    "intent": "Rebuild & mobilize (clean slate)",
    "title": "Yoga Wash - Detox Flow",
    "channel": "Yoga With Adriene",
    "length": "23:32",
    "language": "EN",
    "style": "Detox flow",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Clean-slate reset with detoxifying twists and a reassess-and-choose theme — fresh start after the bleed.",
    "url": "https://www.youtube.com/watch?v=kuSZEZ0fCY0"
  },
  {
    "phase": "Early follicular (post-bleed)",
    "energy": "Low → Moderate",
    "intent": "Rebuild & mobilize (new beginnings)",
    "title": "Yoga For New Beginnings",
    "channel": "Yoga With Adriene",
    "length": "19:03",
    "language": "EN",
    "style": "Fresh-start flow",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Explicitly about new beginnings, fresh breath and opportunity — the book's follicular theme.",
    "url": "https://www.youtube.com/watch?v=tL5xfikyJgI"
  },
  {
    "phase": "Early follicular (post-bleed)",
    "energy": "Low → Moderate",
    "intent": "Rebuild & mobilize (feel good)",
    "title": "Feel Good Flow",
    "channel": "Yoga With Adriene",
    "length": "19:08",
    "language": "EN",
    "style": "Feel-good flow",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Builds some strength while staying present; pitched for 'meh' energy days — the post-bleed ramp.",
    "url": "https://www.youtube.com/watch?v=1-AJwAjoWR0"
  },
  {
    "phase": "Early follicular (post-bleed)",
    "energy": "Low → Moderate",
    "intent": "Rebuild & mobilize (gentle start)",
    "title": "Gentle Yoga - 25 Minute Morning Yoga Sequence",
    "channel": "Yoga With Adriene",
    "length": "25:54",
    "language": "EN",
    "style": "Gentle morning flow",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Gentle but revitalizing morning practice at a nice tempo; a commenter used it to come back after illness — easing back in.",
    "url": "https://www.youtube.com/watch?v=jsLAc-2y0bE"
  },
  {
    "phase": "Early follicular (post-bleed)",
    "energy": "Low → Moderate",
    "intent": "Rebuild & mobilize (foundations of flow)",
    "title": "Yoga for Beginners - Foundations of Flow",
    "channel": "Yoga With Adriene",
    "length": "19:49",
    "language": "EN",
    "style": "Vinyasa basics",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Back-to-basics vinyasa foundations; commenters call it a slower flow — ramp-up.",
    "url": "https://www.youtube.com/watch?v=1p-ayBIRRHs"
  },
  {
    "phase": "Early follicular (post-bleed)",
    "energy": "Low → Moderate",
    "intent": "Rebuild & mobilize (complete beginners)",
    "title": "Yoga For Complete Beginners - 20 Minute Home Yoga Workout!",
    "channel": "Yoga With Adriene",
    "length": "23:45",
    "language": "EN",
    "style": "Beginner foundations",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Foundation-building for total beginners — the gentlest ramp back in.",
    "url": "https://www.youtube.com/watch?v=v7AYKMP6rOE"
  },
  {
    "phase": "Early follicular (post-bleed)",
    "energy": "Low → Moderate",
    "intent": "Rebuild & mobilize (side body)",
    "title": "Travel Yoga: Side Body Sequence",
    "channel": "Yoga With Adriene",
    "length": "22:32",
    "language": "EN",
    "style": "Mindful hatha",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Slow, mindful side-body opening that wakes the body up gently — for coming back after travel or injury.",
    "url": "https://www.youtube.com/watch?v=YshyQQkjSHo"
  },
  {
    "phase": "Early follicular (post-bleed)",
    "energy": "Low → Moderate",
    "intent": "Rebuild & mobilize (gentle morning)",
    "title": "Morning Yoga for Beginners - Gentle Morning Yoga",
    "channel": "Yoga With Adriene",
    "length": "21:50",
    "language": "EN",
    "style": "Gentle morning",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Gentle morning practice for all levels to start fresh — easing back in.",
    "url": "https://www.youtube.com/watch?v=GnHTeHAZQhM"
  },
  {
    "phase": "Mid follicular (rising)",
    "energy": "Moderate",
    "intent": "Open & expand (stretch + strength)",
    "title": "20 min Morning Yoga Flow – Daily Stretch & Strength Routine",
    "channel": "Yoga with Kassandra",
    "length": "20 min",
    "language": "EN",
    "style": "Vinyasa flow",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Balanced flow that feels 'bright' without being too intense.",
    "url": "https://www.youtube.com/watch?v=EuAwhogdukQ"
  },
  {
    "phase": "Mid follicular (rising)",
    "energy": "Moderate",
    "intent": "Open & expand (move stuck energy)",
    "title": "Move that Energy! – a 20 Minute Yoga Class",
    "channel": "Five Parks Yoga",
    "length": "≈20 min",
    "language": "EN",
    "style": "Flow (mood boost)",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Great 'reset' flow—energizing but still mindful.",
    "url": "https://www.youtube.com/watch?v=AweT8J15UcY"
  },
  {
    "phase": "Mid follicular (rising)",
    "energy": "Moderate",
    "intent": "Open & expand (feel-good daily ritual)",
    "title": "20 Minute Everyday Yoga Flow | Daily Routine To Feel Your Best",
    "channel": "Charlie Follows",
    "length": "20 min",
    "language": "EN",
    "style": "Vinyasa (playful)",
    "breathFocus": "Med",
    "modifications": "Some options",
    "notes": "Creative transitions + upbeat vibe; choose when you want to feel 'in motion'.",
    "url": "https://www.youtube.com/watch?v=xE_pGjpycac"
  },
  {
    "phase": "Mid follicular (rising)",
    "energy": "Moderate",
    "intent": "Open & expand (Spanish flow)",
    "title": "Práctica de Flow para todo el cuerpo | 20 Min. de Yoga",
    "channel": "Yoga con Adriene en Español",
    "length": "20 min",
    "language": "ES",
    "style": "Flow",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Adriene-style cueing in Spanish (audio is auto-dubbed on some uploads).",
    "url": "https://www.youtube.com/watch?v=VwtspIZIktM"
  },
  {
    "phase": "Mid follicular (rising)",
    "energy": "Moderate",
    "intent": "Open & expand (open & build)",
    "title": "Breathing Room - Opening Flow",
    "channel": "Yoga With Adriene",
    "length": "25:04",
    "language": "EN",
    "style": "Heart-opening flow",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Heart-opening with warriors, side plank and wild thing; framed around welcoming new possibility — rising energy, novelty.",
    "url": "https://www.youtube.com/watch?v=MEHCa1xUr5A"
  },
  {
    "phase": "Mid follicular (rising)",
    "energy": "Moderate",
    "intent": "Open & expand (agility & focus)",
    "title": "Yoga For Tennis Players",
    "channel": "Yoga With Adriene",
    "length": "21:47",
    "language": "EN",
    "style": "Dynamic flow (sport)",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Dynamic, playful sport-themed flow for shoulders, hips, wrists — something new, moderate-high.",
    "url": "https://www.youtube.com/watch?v=bfFXJq9MMYs"
  },
  {
    "phase": "Mid follicular (rising)",
    "energy": "Moderate",
    "intent": "Open & expand (hips)",
    "title": "20-Minute Yoga For Hips | Feel Good Flow",
    "channel": "Yoga With Adriene",
    "length": "23:32",
    "language": "EN",
    "style": "Hip flow (balance)",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Stability plus flexibility with one-legged work; commenters broke a sweat — moderate-high.",
    "url": "https://www.youtube.com/watch?v=zwoVcrdmLOE"
  },
  {
    "phase": "Mid follicular (rising)",
    "energy": "Moderate",
    "intent": "Open & expand (new day)",
    "title": "Morning Yoga Flow | 20-Minute Morning Yoga Practice",
    "channel": "Yoga With Adriene",
    "length": "21:47",
    "language": "EN",
    "style": "Strengthening morning flow",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Blank-canvas new-day framing with a fiery, strengthening core-focused flow — follicular fresh start with challenge.",
    "url": "https://www.youtube.com/watch?v=LqXZ628YNj4"
  },
  {
    "phase": "Mid follicular (rising)",
    "energy": "Moderate",
    "intent": "Open & expand (shift perspective)",
    "title": "Yoga To Shift Perspective | 20-Minute Yoga Flow",
    "channel": "Yoga With Adriene",
    "length": "20:17",
    "language": "EN",
    "style": "Strong heart-opening flow",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Warming, 'strong and spicy' flow about seeing things a new way and finding creative solutions — follicular novelty with real effort.",
    "url": "https://www.youtube.com/watch?v=icfwMWYDeac"
  },
  {
    "phase": "Mid follicular (rising)",
    "energy": "Moderate",
    "intent": "Open & expand (vitality)",
    "title": "Full Body Flow | 20-Minute Yoga Practice",
    "channel": "Yoga With Adriene",
    "length": "19:18",
    "language": "EN",
    "style": "Full-body flow",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Heat-building full-body flow for strength and mobility — rising energy.",
    "url": "https://www.youtube.com/watch?v=b1H3xO3x_Js"
  },
  {
    "phase": "Mid follicular (rising)",
    "energy": "Moderate",
    "intent": "Open & expand (full body)",
    "title": "Reunite With Your Body | 19-Minute Total Body Yoga",
    "channel": "Yoga With Adriene",
    "length": "18:47",
    "language": "EN",
    "style": "Vinyasa",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Full-body vinyasa that turns up the heat; a commenter says it woke her up — rising energy.",
    "url": "https://www.youtube.com/watch?v=CxuDcHCduw0"
  },
  {
    "phase": "Mid follicular (rising)",
    "energy": "Moderate",
    "intent": "Open & expand (beginner's mind)",
    "title": "Yoga For Beginners Mind",
    "channel": "Yoga With Adriene",
    "length": "21:33",
    "language": "EN",
    "style": "Open, exploratory flow",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Drop what you think you know and stay open to new possibilities — follicular novelty.",
    "url": "https://www.youtube.com/watch?v=0eJoUIBhLkE"
  },
  {
    "phase": "Mid follicular (rising)",
    "energy": "Moderate",
    "intent": "Open & expand (stability & focus)",
    "title": "Yoga for Golfers",
    "channel": "Yoga With Adriene",
    "length": "20:44",
    "language": "EN",
    "style": "Sport-themed flow",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Core stability, range of motion and focus; commenters say it's fun — a novel pick for rising energy.",
    "url": "https://www.youtube.com/watch?v=MPLYc7qsTI4"
  },
  {
    "phase": "Mid follicular (rising)",
    "energy": "Moderate",
    "intent": "Open & expand (shoulders & core)",
    "title": "Yoga For Swimmers",
    "channel": "Yoga With Adriene",
    "length": "18:06",
    "language": "EN",
    "style": "Full-body sport flow",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Shoulders, chest, spine, legs and core with a sensation-over-shape approach — moderate.",
    "url": "https://www.youtube.com/watch?v=WymRLcDo1ek"
  },
  {
    "phase": "Mid follicular (rising)",
    "energy": "Moderate",
    "intent": "Open & expand (crow)",
    "title": "Crow Practice",
    "channel": "Yoga With Adriene",
    "length": "24:20",
    "language": "EN",
    "style": "Skill-building",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Builds step by step toward crow pose — learning a new skill suits follicular novelty.",
    "url": "https://www.youtube.com/watch?v=A7U_M3JvblM"
  },
  {
    "phase": "Mid follicular (rising)",
    "energy": "Moderate",
    "intent": "Open & expand (revolved side angle)",
    "title": "Revolved Side Angle Pose - 20 Minute Practice",
    "channel": "Yoga With Adriene",
    "length": "19:54",
    "language": "EN",
    "style": "Pose foundations",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Prep and learn a challenging twisting pose; shaky legs in the comments — learning something new.",
    "url": "https://www.youtube.com/watch?v=B-NxMApGq4w"
  },
  {
    "phase": "Mid follicular (rising)",
    "energy": "Moderate",
    "intent": "Open & expand (headstand)",
    "title": "Head Stand Yoga Pose - How To Do a Headstand for Beginners",
    "channel": "Yoga With Adriene",
    "length": "18:00",
    "language": "EN",
    "style": "Pose foundations",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Step-by-step headstand learning with a playful, confidence-building angle — follicular novelty.",
    "url": "https://www.youtube.com/watch?v=V1HbXt5ZRlg"
  },
  {
    "phase": "Mid follicular (rising)",
    "energy": "Moderate",
    "intent": "Open & expand (energizing morning)",
    "title": "Morning Yoga - Energizing Morning Sequence",
    "channel": "Yoga With Adriene",
    "length": "24:07",
    "language": "EN",
    "style": "Energizing morning flow",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Stretches and strengthens with a 'start fresh' morning framing; commenters get wobbly in high lunge — rising energy.",
    "url": "https://www.youtube.com/watch?v=K-Ina_WW4Yc"
  },
  {
    "phase": "Mid follicular (rising)",
    "energy": "Moderate",
    "intent": "Open & expand (freedom)",
    "title": "Freedom Flow!",
    "channel": "Yoga With Adriene",
    "length": "18:11",
    "language": "EN",
    "style": "Vinyasa",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "All-levels vinyasa about finding your own expression and sweating it out — rising, playful energy.",
    "url": "https://www.youtube.com/watch?v=HxZ6Xz73nGA"
  },
  {
    "phase": "Ovulation (peak)",
    "energy": "High",
    "intent": "Power & play (sweaty, strong)",
    "title": "15 MIN Morning Yoga Power Flow | Full Body Stretch & Workout",
    "channel": "Yoga With Tim",
    "length": "15 min",
    "language": "EN",
    "style": "Power vinyasa",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Short, strong, and sweaty—great when you want heat without a long practice.",
    "url": "https://www.youtube.com/watch?v=tq-vxTqoiHw"
  },
  {
    "phase": "Ovulation (peak)",
    "energy": "High",
    "intent": "Power & play (energizing full-body)",
    "title": "Try this 20 min Yoga Flow | Energising Full Body Routine",
    "channel": "Charlie Follows",
    "length": "20 min",
    "language": "EN",
    "style": "Energizing vinyasa",
    "breathFocus": "Med",
    "modifications": "Some options",
    "notes": "Dynamic sequence; ideal for 'I want to move!' days.",
    "url": "https://www.youtube.com/watch?v=k3ybhxZewLg"
  },
  {
    "phase": "Ovulation (peak)",
    "energy": "High",
    "intent": "Power & play (quick boost)",
    "title": "10 Minute Morning Yoga – Energy Boost Yoga",
    "channel": "Yoga with Kassandra",
    "length": "10 min",
    "language": "EN",
    "style": "Quick flow",
    "breathFocus": "Med",
    "modifications": "Yes",
    "notes": "Perfect when you're short on time but want a 'spark'.",
    "url": "https://www.youtube.com/watch?v=w8nPq-MtGOA"
  },
  {
    "phase": "Ovulation (peak)",
    "energy": "High",
    "intent": "Power & play (Spanish full-body flow)",
    "title": "YOGA FLOW PARA TODO CUERPO EN 20 MINUTOS",
    "channel": "MalovaElena",
    "length": "20 min",
    "language": "ES",
    "style": "Vinyasa",
    "breathFocus": "Med",
    "modifications": "Some options",
    "notes": "A solid Spanish flow option for energetic days.",
    "url": "https://www.youtube.com/watch?v=IM9uK5V77gM"
  },
  {
    "phase": "Ovulation (peak)",
    "energy": "High",
    "intent": "Power & play (heart & upper body)",
    "title": "Chest & Upper Body Opening Flow",
    "channel": "Yoga With Adriene",
    "length": "24:17",
    "language": "EN",
    "style": "Upper-body flow + strength",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Described as a workout for body and soul with strengthening and heart-space opening; new pose variations.",
    "url": "https://www.youtube.com/watch?v=CZJVeUD_Ou8"
  },
  {
    "phase": "Ovulation (peak)",
    "energy": "High",
    "intent": "Power & play (open heart)",
    "title": "Love Wins Yoga",
    "channel": "Yoga With Adriene",
    "length": "21:36",
    "language": "EN",
    "style": "Heart-opening flow",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Open-heart, all-are-welcome practice; also pitched for down days — connection theme.",
    "url": "https://www.youtube.com/watch?v=npfgUL_rOsw"
  },
  {
    "phase": "Ovulation (peak)",
    "energy": "High",
    "intent": "Power & play (power)",
    "title": "20-Minute Intermediate Power Yoga",
    "channel": "Yoga With Adriene",
    "length": "23:31",
    "language": "EN",
    "style": "Power yoga",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Intermediate full-body power flow; commenters found it hard — peak intensity.",
    "url": "https://www.youtube.com/watch?v=ZbtVVYBLCug"
  },
  {
    "phase": "Ovulation (peak)",
    "energy": "High",
    "intent": "Power & play (celebrate)",
    "title": "Yoga For Celebrating | 25-Minute Yoga Practice",
    "channel": "Yoga With Adriene",
    "length": "25:11",
    "language": "EN",
    "style": "Celebratory flow",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Built for high times and community celebration — outgoing ovulatory mood.",
    "url": "https://www.youtube.com/watch?v=GK28p-OdM4Y"
  },
  {
    "phase": "Ovulation (peak)",
    "energy": "High",
    "intent": "Power & play (joy)",
    "title": "Yoga Joy | 20-Minute Full Body Vinyasa Flow",
    "channel": "Yoga With Adriene",
    "length": "19:04",
    "language": "EN",
    "style": "Strengthening vinyasa",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Uplifting, strengthening vinyasa that builds heat and moves stuck energy — high, bright energy.",
    "url": "https://www.youtube.com/watch?v=P8uHMMmWMHQ"
  },
  {
    "phase": "Ovulation (peak)",
    "energy": "High",
    "intent": "Power & play (voice)",
    "title": "Throat Chakra Yoga | 20-Minute Yoga Practice",
    "channel": "Yoga With Adriene",
    "length": "21:38",
    "language": "EN",
    "style": "Gentle throat/heart openers",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Throat-chakra practice about finding your voice and speaking your truth — the book's ovulatory communication theme, though the movement itself is gentle.",
    "url": "https://www.youtube.com/watch?v=BSaT6SOWZsM"
  },
  {
    "phase": "Ovulation (peak)",
    "energy": "High",
    "intent": "Power & play (feel your best)",
    "title": "Yoga To Feel Your Best | 22-Minute Home Yoga",
    "channel": "Yoga With Adriene",
    "length": "22:59",
    "language": "EN",
    "style": "Feel-good stretch flow",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "About feeling and looking your best — the book notes that urge peaks at ovulation. Movement is moderate.",
    "url": "https://www.youtube.com/watch?v=BPK9WNtpBgk"
  },
  {
    "phase": "Ovulation (peak)",
    "energy": "High",
    "intent": "Power & play (deep core)",
    "title": "Total Body Yoga - 20-Minute Deep Core Yoga",
    "channel": "Yoga With Adriene",
    "length": "21:04",
    "language": "EN",
    "style": "Deep-core strength",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Strength-building core session that lights a fire, finishing with vinyasa — strenuous.",
    "url": "https://www.youtube.com/watch?v=BPobdbmzY9o"
  },
  {
    "phase": "Ovulation (peak)",
    "energy": "High",
    "intent": "Power & play (connection)",
    "title": "Up Your Connect | 20-Minute Yoga Practice",
    "channel": "Yoga With Adriene",
    "length": "19:00",
    "language": "EN",
    "style": "Celebratory flow",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Framed as a celebration of connection and the ties between people — ovulatory community theme.",
    "url": "https://www.youtube.com/watch?v=Ec2jPvLdjd8"
  },
  {
    "phase": "Ovulation (peak)",
    "energy": "High",
    "intent": "Power & play (core)",
    "title": "Core Power Wake Up",
    "channel": "Yoga With Adriene",
    "length": "23:19",
    "language": "EN",
    "style": "Core power",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Commenters call it hard (hip dips, lots of groaning) — peak intensity.",
    "url": "https://www.youtube.com/watch?v=k2Aw9vZm_0E"
  },
  {
    "phase": "Ovulation (peak)",
    "energy": "High",
    "intent": "Power & play (fire & grace)",
    "title": "Yoga For Dancers",
    "channel": "Yoga With Adriene",
    "length": "23:53",
    "language": "EN",
    "style": "Strength + balance",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Tones the whole body; commenters call it one of the hardest, especially the balance work — peak intensity.",
    "url": "https://www.youtube.com/watch?v=KRGwvLkJZEI"
  },
  {
    "phase": "Ovulation (peak)",
    "energy": "High",
    "intent": "Power & play (find your voice)",
    "title": "Yoga For Actors",
    "channel": "Yoga With Adriene",
    "length": "19:39",
    "language": "EN",
    "style": "Warm-up + voice",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Hands-free warm-up for finding your voice, confidence and presence — the book's ovulatory communication theme.",
    "url": "https://www.youtube.com/watch?v=oSUKWSDjvOY"
  },
  {
    "phase": "Ovulation (peak)",
    "energy": "High",
    "intent": "Power & play (balance & tone)",
    "title": "Balancing Ocean Flow",
    "channel": "Yoga With Adriene",
    "length": "25:03",
    "language": "EN",
    "style": "Intermediate strength flow",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Invigorating intermediate workout; commenters say it's far harder than the name suggests — peak.",
    "url": "https://www.youtube.com/watch?v=Ido0fK6uBi8"
  },
  {
    "phase": "Ovulation (peak)",
    "energy": "High",
    "intent": "Power & play (let it go)",
    "title": "Let It Go Yoga Flow",
    "channel": "Yoga With Adriene",
    "length": "19:48",
    "language": "EN",
    "style": "Swift vinyasa",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Swift, fiery vinyasa: 'feel the burn' — peak intensity.",
    "url": "https://www.youtube.com/watch?v=iIHCWMplHsw"
  },
  {
    "phase": "Ovulation (peak)",
    "energy": "High",
    "intent": "Power & play (tone)",
    "title": "Yoga Tone | Yoga For Weight Loss",
    "channel": "Yoga With Adriene",
    "length": "22:30",
    "language": "EN",
    "style": "Strength vinyasa",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Swift vinyasa for strength and endurance — peak intensity.",
    "url": "https://www.youtube.com/watch?v=4O-b24WKdYA"
  },
  {
    "phase": "Ovulation (peak)",
    "energy": "High",
    "intent": "Power & play (vinyasa)",
    "title": "Yoga Flow | 20 Minute Vinyasa Sequence",
    "channel": "Yoga With Adriene",
    "length": "19:18",
    "language": "EN",
    "style": "Fast vinyasa",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Fast-paced vinyasa that builds strength; commenters call it the quickest 20 minutes — high energy.",
    "url": "https://www.youtube.com/watch?v=xmeNZI8inWI"
  },
  {
    "phase": "Ovulation (peak)",
    "energy": "High",
    "intent": "Power & play (detox & digestion)",
    "title": "Detox Yoga | 20 Minute Yoga Flow for Detox and Digestion",
    "channel": "Yoga With Adriene",
    "length": "20:37",
    "language": "EN",
    "style": "Sweaty detox flow",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Digestion theme, but designed to make you sweat with strength and twists; a commenter once found it the hardest workout — too intense for late luteal.",
    "url": "https://www.youtube.com/watch?v=cBPP_izKKSs"
  },
  {
    "phase": "Early luteal (post-ovulation)",
    "energy": "Moderate",
    "intent": "Ground & strengthen (stability + power)",
    "title": "20 Min Yoga for Strength & Flexibility | Full Body Flow (All Levels)",
    "channel": "Yoga With Tim",
    "length": "20 min",
    "language": "EN",
    "style": "Strength flow",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Strong-but-steady: great for feeling capable and grounded.",
    "url": "https://www.youtube.com/watch?v=sZLSBMrEZwA"
  },
  {
    "phase": "Early luteal (post-ovulation)",
    "energy": "Moderate",
    "intent": "Ground & strengthen (steady daily flow)",
    "title": "20 minute Morning Yoga Flow ☀️ Every Day Full Body Yoga (All Levels)",
    "channel": "SarahBethYoga",
    "length": "20 min",
    "language": "EN",
    "style": "Morning flow",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Clear, no-fuss cueing; consistent pacing.",
    "url": "https://www.youtube.com/watch?v=a0GaOvCfjyE"
  },
  {
    "phase": "Early luteal (post-ovulation)",
    "energy": "Moderate",
    "intent": "Ground & strengthen (daily essentials)",
    "title": "20 Min Daily Yoga Flow | Every Day Full Body Yoga For All Levels",
    "channel": "Charlie Follows",
    "length": "20 min",
    "language": "EN",
    "style": "Steady vinyasa",
    "breathFocus": "Med",
    "modifications": "Some options",
    "notes": "A 'basics done well' flow to keep you consistent.",
    "url": "https://www.youtube.com/watch?v=sOjXETbN32g"
  },
  {
    "phase": "Early luteal (post-ovulation)",
    "energy": "Moderate",
    "intent": "Ground & strengthen (Spanish vinyasa)",
    "title": "YOGA PARA TODO CUERPO | VINYASA YOGA | YOGA EN CASA 20 MIN",
    "channel": "MalovaElena",
    "length": "20 min",
    "language": "ES",
    "style": "Vinyasa",
    "breathFocus": "Med",
    "modifications": "Some options",
    "notes": "Good 'daily practice' option in Spanish.",
    "url": "https://www.youtube.com/watch?v=PGaxPUsTZD4"
  },
  {
    "phase": "Early luteal (post-ovulation)",
    "energy": "Moderate",
    "intent": "Ground & strengthen (core & confidence)",
    "title": "Return - 4 - Center",
    "channel": "Yoga With Adriene",
    "length": "19:37",
    "language": "EN",
    "style": "Core strength (gentle)",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Steady, supportive core strengthening; strong but not peak intensity.",
    "url": "https://www.youtube.com/watch?v=pvpD2MfzlZ0"
  },
  {
    "phase": "Early luteal (post-ovulation)",
    "energy": "Moderate",
    "intent": "Ground & strengthen (calves & circulation)",
    "title": "Yoga For Your Calves (and Ankles)",
    "channel": "Yoga With Adriene",
    "length": "23:21",
    "language": "EN",
    "style": "Lower-body standing",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Challenging standing leg work (commenters struggle to stay up); circulation focus could also suit late luteal water retention.",
    "url": "https://www.youtube.com/watch?v=2XhJ63OQ7Ww"
  },
  {
    "phase": "Early luteal (post-ovulation)",
    "energy": "Moderate",
    "intent": "Ground & strengthen (bone health)",
    "title": "Yoga For Bone Health",
    "channel": "Yoga With Adriene",
    "length": "21:30",
    "language": "EN",
    "style": "Strength + balance",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Strength, posture, joint stability and balance — steady strength work.",
    "url": "https://www.youtube.com/watch?v=raUEsDttCL4"
  },
  {
    "phase": "Early luteal (post-ovulation)",
    "energy": "Moderate",
    "intent": "Ground & strengthen (abs)",
    "title": "20-Minute Yoga for Abs | Feel Good Flow",
    "channel": "Yoga With Adriene",
    "length": "21:34",
    "language": "EN",
    "style": "Core flow",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Core strengthening designed to leave the nervous system calm; one commenter felt weak on her period — better before, not during.",
    "url": "https://www.youtube.com/watch?v=6uVSkvWO7As"
  },
  {
    "phase": "Early luteal (post-ovulation)",
    "energy": "Moderate",
    "intent": "Ground & strengthen (core)",
    "title": "Reunite With Your Center | 19-Minute Yoga for Core",
    "channel": "Yoga With Adriene",
    "length": "18:47",
    "language": "EN",
    "style": "Core",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Core heat and stability; commenters found it a challenge — steady strength.",
    "url": "https://www.youtube.com/watch?v=SrN9pBY0KZs"
  },
  {
    "phase": "Early luteal (post-ovulation)",
    "energy": "Moderate",
    "intent": "Ground & strengthen (stamina)",
    "title": "Yoga For Runners - Physical & Mental Stamina",
    "channel": "Yoga With Adriene",
    "length": "20:20",
    "language": "EN",
    "style": "Lower-body strength + stretch",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Keeps legs strong and flexible with a stamina focus — steady strength.",
    "url": "https://www.youtube.com/watch?v=plL13JF5BHA"
  },
  {
    "phase": "Early luteal (post-ovulation)",
    "energy": "Moderate",
    "intent": "Ground & strengthen (confidence)",
    "title": "Yoga For Teens",
    "channel": "Yoga With Adriene",
    "length": "20:56",
    "language": "EN",
    "style": "Core + back strength",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Lights a fire in the core and strengthens the back, with a confidence theme — steady strength.",
    "url": "https://www.youtube.com/watch?v=7kgZnJqzNaU"
  },
  {
    "phase": "Early luteal (post-ovulation)",
    "energy": "Moderate",
    "intent": "Ground & strengthen (center)",
    "title": "Finding Your Center",
    "channel": "Yoga With Adriene",
    "length": "18:33",
    "language": "EN",
    "style": "Core + pranayama",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Short core and breath practice; the description gives little detail on intensity.",
    "url": "https://www.youtube.com/watch?v=rgeTSarKZ8c"
  },
  {
    "phase": "Early luteal (post-ovulation)",
    "energy": "Moderate",
    "intent": "Ground & strengthen (insecurity → power)",
    "title": "Yoga For Insecurity",
    "channel": "Yoga With Adriene",
    "length": "23:48",
    "language": "EN",
    "style": "Strength flow",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Recognizing your own power; commenters mention several side planks — moderate strength.",
    "url": "https://www.youtube.com/watch?v=5pZO7-RK2cE"
  },
  {
    "phase": "Early luteal (post-ovulation)",
    "energy": "Moderate",
    "intent": "Ground & strengthen (healthy body)",
    "title": "Healthy Body Yoga - 20 Minute Yoga Practice",
    "channel": "Yoga With Adriene",
    "length": "20:52",
    "language": "EN",
    "style": "Full-body strength",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Core, hips and stability pitched as a workout you enjoy — steady strength.",
    "url": "https://www.youtube.com/watch?v=ZiQh8jA5tVM"
  },
  {
    "phase": "Early luteal (post-ovulation)",
    "energy": "Moderate",
    "intent": "Ground & strengthen (core ritual)",
    "title": "Core Strength Ritual",
    "channel": "Yoga With Adriene",
    "length": "22:27",
    "language": "EN",
    "style": "Core strength",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Demanding core session; commenters head to child's pose often — strong.",
    "url": "https://www.youtube.com/watch?v=CRKmB-78elI"
  },
  {
    "phase": "Early luteal (post-ovulation)",
    "energy": "Moderate",
    "intent": "Ground & strengthen (digestion)",
    "title": "Yoga For Digestion Flow",
    "channel": "Yoga With Adriene",
    "length": "25:20",
    "language": "EN",
    "style": "Swift challenging flow",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Digestion theme, but it's a challenging, swift sequence with abs and a dance finish — too intense for the final luteal days.",
    "url": "https://www.youtube.com/watch?v=zJWGhHsPMVQ"
  },
  {
    "phase": "Mid luteal (settling)",
    "energy": "Moderate → Low",
    "intent": "Regulate & release (hips + low back)",
    "title": "20 Min Yoga For Hips & Lower Back Release | Deep Yoga Stretch",
    "channel": "Yoga With Tim",
    "length": "20 min",
    "language": "EN",
    "style": "Mobility / Deep stretch",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Excellent for bloating/back tension days—deep but controlled.",
    "url": "https://www.youtube.com/watch?v=IQe2RR_Bgzo"
  },
  {
    "phase": "Mid luteal (settling)",
    "energy": "Moderate → Low",
    "intent": "Regulate & release (anxiety reset)",
    "title": "Quick Escape – 20 Minute Yoga Class",
    "channel": "Five Parks Yoga",
    "length": "21:31",
    "language": "EN",
    "style": "Flow (nervous system reset)",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Specifically framed for anxiety/overwhelm—move + breathe to downshift.",
    "url": "https://www.youtube.com/watch?v=dFmx0xMsAgo"
  },
  {
    "phase": "Mid luteal (settling)",
    "energy": "Moderate → Low",
    "intent": "Regulate & release (feel-good + release tension)",
    "title": "20 Min Yoga to FEEL GOOD! (Beginner Friendly Yoga)",
    "channel": "Yoga With Bird",
    "length": "20 min",
    "language": "EN",
    "style": "Flow + stretch",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Supportive, soothing tone; good when emotions are 'close to the surface'.",
    "url": "https://www.youtube.com/watch?v=chuR6NHXviU"
  },
  {
    "phase": "Mid luteal (settling)",
    "energy": "Moderate → Low",
    "intent": "Regulate & release (breath in Spanish)",
    "title": "20 minutos de yoga para calmar la ansiedad (Pranayama) – Xuan Lan",
    "channel": "Xuan Lan Yoga",
    "length": "≈20 min",
    "language": "ES",
    "style": "Pranayama (breathwork)",
    "breathFocus": "Very high",
    "modifications": "N/A (seated)",
    "notes": "Breath-only option for days you want calm without much movement.",
    "url": "https://www.youtube.com/watch?v=UPjochWx44w"
  },
  {
    "phase": "Mid luteal (settling)",
    "energy": "Moderate → Low",
    "intent": "Regulate & release (posture & upper back)",
    "title": "Yoga for Better Posture | Chest, Shoulders & Upper Back",
    "channel": "Yoga With Adriene",
    "length": "25:13",
    "language": "EN",
    "style": "Therapeutic / posture",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Alignment-focused heart openers to counter slouching; detail-oriented, moderate effort.",
    "url": "https://www.youtube.com/watch?v=eQeNhnAHXP4"
  },
  {
    "phase": "Mid luteal (settling)",
    "energy": "Moderate → Low",
    "intent": "Regulate & release (patience & surrender)",
    "title": "Trust The Process",
    "channel": "Yoga With Adriene",
    "length": "21:46",
    "language": "EN",
    "style": "Grounding flow",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Grounding, inward, letting go of control — settling energy, moderate.",
    "url": "https://www.youtube.com/watch?v=5qudWyJNlMA"
  },
  {
    "phase": "Mid luteal (settling)",
    "energy": "Moderate → Low",
    "intent": "Regulate & release (self-study)",
    "title": "Prana - Day 7",
    "channel": "Yoga With Adriene",
    "length": "23:48",
    "language": "EN",
    "style": "Subtle / alignment",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Relaxed attention, posture alignment, subtle-body self-study — detail-oriented, calmer.",
    "url": "https://www.youtube.com/watch?v=EtJPA0dVTDs"
  },
  {
    "phase": "Mid luteal (settling)",
    "energy": "Moderate → Low",
    "intent": "Regulate & release (rooted & slow)",
    "title": "Prana - Day 4",
    "channel": "Yoga With Adriene",
    "length": "22:51",
    "language": "EN",
    "style": "Standing / mobility",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Rooted standing work and a mobility flow; explicitly asks you to slow down rather than push.",
    "url": "https://www.youtube.com/watch?v=pt7AFyWtPGE"
  },
  {
    "phase": "Mid luteal (settling)",
    "energy": "Moderate → Low",
    "intent": "Regulate & release (flexible mind)",
    "title": "Yoga for Flexible Mind and Body",
    "channel": "Yoga With Adriene",
    "length": "22:51",
    "language": "EN",
    "style": "Stretch + contemplation",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Explicitly about not over-extending or hustling; stretch and contemplate — settling luteal energy.",
    "url": "https://www.youtube.com/watch?v=xFEAOzWLx8Y"
  },
  {
    "phase": "Mid luteal (settling)",
    "energy": "Moderate → Low",
    "intent": "Regulate & release (upper back)",
    "title": "Upper Back Love | Yoga For Back Pain",
    "channel": "Yoga With Adriene",
    "length": "23:24",
    "language": "EN",
    "style": "Upper-back therapeutic",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Tension relief and posture work for the upper back — moderate, detail-oriented.",
    "url": "https://www.youtube.com/watch?v=lMTyp5npt78"
  },
  {
    "phase": "Mid luteal (settling)",
    "energy": "Moderate → Low",
    "intent": "Regulate & release (grounding & balance)",
    "title": "Anchor In Hope | 18-Minute Yoga Flow",
    "channel": "Yoga With Adriene",
    "length": "18:04",
    "language": "EN",
    "style": "Grounding flow",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Short flow of grounding hip openers and energizing heart openers to restore balance — settling energy.",
    "url": "https://www.youtube.com/watch?v=RoSO3_0Ufr0"
  },
  {
    "phase": "Mid luteal (settling)",
    "energy": "Moderate → Low",
    "intent": "Regulate & release (self-respect)",
    "title": "Yoga For Self Respect | 20 Minute Practice",
    "channel": "Yoga With Adriene",
    "length": "20:27",
    "language": "EN",
    "style": "Inward spine + breath",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Dial inward, lengthen the spine, deepen the breath — settling.",
    "url": "https://www.youtube.com/watch?v=sJfkWNW183U"
  },
  {
    "phase": "Mid luteal (settling)",
    "energy": "Moderate → Low",
    "intent": "Regulate & release (posture)",
    "title": "Heart Chakra Yoga For Beginners",
    "channel": "Yoga With Adriene",
    "length": "23:50",
    "language": "EN",
    "style": "Upper back + heart",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Gentle heart-space practice that mainly targets upper back, shoulders and posture — settling.",
    "url": "https://www.youtube.com/watch?v=iL_fhffZopY"
  },
  {
    "phase": "Mid luteal (settling)",
    "energy": "Moderate → Low",
    "intent": "Regulate & release (posture & hands)",
    "title": "Yoga For Musicians",
    "channel": "Yoga With Adriene",
    "length": "25:08",
    "language": "EN",
    "style": "Therapeutic upper body",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Mindful, therapeutic work for neck, shoulders, arms and wrists — detail-oriented.",
    "url": "https://www.youtube.com/watch?v=NXEoc1kN4yo"
  },
  {
    "phase": "Mid luteal (settling)",
    "energy": "Moderate → Low",
    "intent": "Regulate & release (spine)",
    "title": "Yoga For Scoliosis",
    "channel": "Yoga With Adriene",
    "length": "25:13",
    "language": "EN",
    "style": "Spine / posture",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Spine-focused posture practice for all levels — moderate, careful work.",
    "url": "https://www.youtube.com/watch?v=UuifgElXjmM"
  },
  {
    "phase": "Mid luteal (settling)",
    "energy": "Moderate → Low",
    "intent": "Regulate & release (psoas)",
    "title": "Yoga For Psoas",
    "channel": "Yoga With Adriene",
    "length": "22:01",
    "language": "EN",
    "style": "Therapeutic hips/psoas",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Mix of release, strengthening and stabilizing for hip and back tension — moderate, careful work.",
    "url": "https://www.youtube.com/watch?v=JsE4csvlUfA"
  },
  {
    "phase": "Mid luteal (settling)",
    "energy": "Moderate → Low",
    "intent": "Regulate & release (cyclists)",
    "title": "Yoga For Cyclists",
    "channel": "Yoga With Adriene",
    "length": "23:37",
    "language": "EN",
    "style": "Well-rounded stretch",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Rounded stretch with core activation and an emphasis on paying attention — moderate, detail-minded.",
    "url": "https://www.youtube.com/watch?v=YWzRE1BiAvw"
  },
  {
    "phase": "Mid luteal (settling)",
    "energy": "Moderate → Low",
    "intent": "Regulate & release (wrists)",
    "title": "Yoga For Wrist Pain",
    "channel": "Yoga With Adriene",
    "length": "22:27",
    "language": "EN",
    "style": "Alignment workshop",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "A workshop on wrist alignment and support — detail-oriented, moderate.",
    "url": "https://www.youtube.com/watch?v=RGEWpPHu69A"
  },
  {
    "phase": "Mid luteal (settling)",
    "energy": "Moderate → Low",
    "intent": "Regulate & release (grounding)",
    "title": "Grounding Yoga Practice | Happy Earth Day!",
    "channel": "Yoga With Adriene",
    "length": "20:27",
    "language": "EN",
    "style": "Grounding poses",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Five grounding poses for an overactive mind — settling.",
    "url": "https://www.youtube.com/watch?v=FQ74ZykbFFE"
  },
  {
    "phase": "Mid luteal (settling)",
    "energy": "Moderate → Low",
    "intent": "Regulate & release (lunch break)",
    "title": "Yoga For Your Lunch Break",
    "channel": "Yoga With Adriene",
    "length": "19:40",
    "language": "EN",
    "style": "Full-body stretch",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Decompress and refocus with a full-body stretch — moderate, practical.",
    "url": "https://www.youtube.com/watch?v=s8RDWogbqh0"
  },
  {
    "phase": "Mid luteal (settling)",
    "energy": "Moderate → Low",
    "intent": "Regulate & release (hamstrings)",
    "title": "Yoga For Hamstrings",
    "channel": "Yoga With Adriene",
    "length": "23:22",
    "language": "EN",
    "style": "Hamstring stretch + stability",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Hamstring flexibility with stability work and back/neck relief; commenters found the 'easy stretch' made their legs shake — moderate, detail-focused.",
    "url": "https://www.youtube.com/watch?v=-Mirm7LKvKk"
  },
  {
    "phase": "Late luteal (premenstrual)",
    "energy": "Low → Moderate",
    "intent": "Creative & inward (yin, introspection)",
    "title": "20 min Morning Yin Yoga – HIPS & HAMSTRINGS",
    "channel": "Yoga with Kassandra",
    "length": "20 min",
    "language": "EN",
    "style": "Yin",
    "breathFocus": "High",
    "modifications": "Yes (props helpful)",
    "notes": "Great for inward days—longer holds + breath awareness.",
    "url": "https://www.youtube.com/watch?v=KyHnpaQkFCI"
  },
  {
    "phase": "Late luteal (premenstrual)",
    "energy": "Low → Moderate",
    "intent": "Creative & inward (slow, soulful)",
    "title": "20 Minute // RELAXING YOGA FLOW // The Yogi Witch",
    "channel": "The Yogi Witch",
    "length": "20 min",
    "language": "EN",
    "style": "Relaxing flow",
    "breathFocus": "High",
    "modifications": "Yes (props suggested)",
    "notes": "A little mystical / seasonal energy; great for reflective mornings.",
    "url": "https://www.youtube.com/watch?v=YWD_09-gwiI"
  },
  {
    "phase": "Late luteal (premenstrual)",
    "energy": "Low",
    "intent": "Creative & inward (nervous system calm)",
    "title": "Unlock Instant Calm: 10 Min Breath-work for Anxiety Relief",
    "channel": "Breathwork video (YouTube)",
    "length": "10 min",
    "language": "EN",
    "style": "Breathwork / Pranayama",
    "breathFocus": "Very high",
    "modifications": "N/A (seated)",
    "notes": "Perfect on tender days when movement feels like 'too much'.",
    "url": "https://www.youtube.com/watch?v=4OwZfOeOrlY"
  },
  {
    "phase": "Late luteal (premenstrual)",
    "energy": "Low",
    "intent": "Creative & inward (Spanish: stress + fatigue)",
    "title": "Yoga Suave para Liberar Estrés, Tensión y Cansancio",
    "channel": "Luly Garza Yoga",
    "length": "25 min",
    "language": "ES",
    "style": "Yoga suave",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Spanish gentle practice for tired / inward days (great for language immersion).",
    "url": "https://www.youtube.com/watch?v=C7WnqEg5x3k"
  },
  {
    "phase": "Late luteal (premenstrual)",
    "energy": "Low → Moderate",
    "intent": "Creative & inward (anxiety & overthinking)",
    "title": "Yoga For Anxiety and Overthinking | 20 Minute Practice",
    "channel": "Yoga With Adriene",
    "length": "19:16",
    "language": "EN",
    "style": "Gentle / calming",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Designed for a scattered, ruminating mind; slows down to rest and release — premenstrual mood support.",
    "url": "https://www.youtube.com/watch?v=Cl3-Ebtefss"
  },
  {
    "phase": "Late luteal (premenstrual)",
    "energy": "Low → Moderate",
    "intent": "Creative & inward (emotions)",
    "title": "Yoga Release | 25-Minute Yoga Practice",
    "channel": "Yoga With Adriene",
    "length": "25:53",
    "language": "EN",
    "style": "Emotional release flow",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Built around processing big emotions; commenters describe crying then calm — premenstrual mood support.",
    "url": "https://www.youtube.com/watch?v=1G5q66RExDU"
  },
  {
    "phase": "Late luteal (premenstrual)",
    "energy": "Low → Moderate",
    "intent": "Creative & inward (spiraling / overwhelm)",
    "title": "Yoga For When You Are Spiraling",
    "channel": "Yoga With Adriene",
    "length": "25:35",
    "language": "EN",
    "style": "Grounding + breathwork",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "For a nervous system on high alert; grounding plus breath — irritability/anxiety days.",
    "url": "https://www.youtube.com/watch?v=HVITxjrNlts"
  },
  {
    "phase": "Late luteal (premenstrual)",
    "energy": "Low → Moderate",
    "intent": "Creative & inward (digestion & low back)",
    "title": "Prana - Day 2",
    "channel": "Yoga With Adriene",
    "length": "22:33",
    "language": "EN",
    "style": "Mindful flow",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Mental-health focus with digestion, low-back and hamstring support — bloating/PMS days.",
    "url": "https://www.youtube.com/watch?v=gZ1DtlOJNMI"
  },
  {
    "phase": "Late luteal (premenstrual)",
    "energy": "Low → Moderate",
    "intent": "Creative & inward (unwind)",
    "title": "Yoga For Chefs | 18-Minute Yoga",
    "channel": "Yoga With Adriene",
    "length": "18:23",
    "language": "EN",
    "style": "Tension-release stretch",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Relieves tightness and gives the thinking mind a break; commenters call it a good wind-down — lower-resistance late-luteal day.",
    "url": "https://www.youtube.com/watch?v=-pv06KbAH5Q"
  },
  {
    "phase": "Late luteal (premenstrual)",
    "energy": "Low → Moderate",
    "intent": "Creative & inward (breath for calm)",
    "title": "Reunite With Your Breath | 19-Minute Breath Practice",
    "channel": "Yoga With Adriene",
    "length": "19:14",
    "language": "EN",
    "style": "Pranayama (floor)",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Breath-only practice low to the ground for anxiety, stress and big emotions — premenstrual calm.",
    "url": "https://www.youtube.com/watch?v=Oy4wvF9Z24A"
  },
  {
    "phase": "Late luteal (premenstrual)",
    "energy": "Low → Moderate",
    "intent": "Creative & inward (change & drain)",
    "title": "Yoga For Change And Drain",
    "channel": "Yoga With Adriene",
    "length": "22:50",
    "language": "EN",
    "style": "Heart/hip openers + lymphatic",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Includes lymphatic movement — a good match for late-luteal water retention and sluggishness.",
    "url": "https://www.youtube.com/watch?v=E3jFEOD2tIU"
  },
  {
    "phase": "Late luteal (premenstrual)",
    "energy": "Low → Moderate",
    "intent": "Creative & inward (social anxiety)",
    "title": "Yoga For Social Anxiety",
    "channel": "Yoga With Adriene",
    "length": "20:15",
    "language": "EN",
    "style": "Gentle grounding",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Gentle, present-moment reset for anxiety — premenstrual mood support.",
    "url": "https://www.youtube.com/watch?v=l1097wYhDOY"
  },
  {
    "phase": "Late luteal (premenstrual)",
    "energy": "Low → Moderate",
    "intent": "Creative & inward (blood & lymph flow)",
    "title": "Yoga For Healthy Blood Flow",
    "channel": "Yoga With Adriene",
    "length": "19:51",
    "language": "EN",
    "style": "Circulation flow + self-massage",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Built to clear stagnation and move blood and lymph, with self-massage — suits late-luteal water retention and sluggishness.",
    "url": "https://www.youtube.com/watch?v=dyC0TWy8NzU"
  },
  {
    "phase": "Late luteal (premenstrual)",
    "energy": "Low → Moderate",
    "intent": "Creative & inward (wind down)",
    "title": "Wind Down Yoga | 25-Minute Calming Yoga Practice",
    "channel": "Yoga With Adriene",
    "length": "25:47",
    "language": "EN",
    "style": "Grounding wind-down",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "For shaking off bad energy and choosing something kind over something destructive — irritable premenstrual evenings.",
    "url": "https://www.youtube.com/watch?v=zJOCGSwB8v4"
  },
  {
    "phase": "Late luteal (premenstrual)",
    "energy": "Low → Moderate",
    "intent": "Creative & inward (emotions)",
    "title": "Head & Heart Reset",
    "channel": "Yoga With Adriene",
    "length": "24:55",
    "language": "EN",
    "style": "Heart-centered reset",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Reset for when emotions get the best of you — premenstrual mood support.",
    "url": "https://www.youtube.com/watch?v=G4QUhyW-muE"
  },
  {
    "phase": "Late luteal (premenstrual)",
    "energy": "Low → Moderate",
    "intent": "Creative & inward (headache)",
    "title": "Yoga For Migraines",
    "channel": "Yoga With Adriene",
    "length": "23:45",
    "language": "EN",
    "style": "Gentle + pranayama",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Gentle, healing practice for headaches and migraines — headache is one of the book's named premenstrual symptoms.",
    "url": "https://www.youtube.com/watch?v=QFkAl5wHEbg"
  },
  {
    "phase": "Late luteal (premenstrual)",
    "energy": "Low → Moderate",
    "intent": "Creative & inward (calm nerves)",
    "title": "Yoga to Calm Your Nerves | Calming Yoga",
    "channel": "Yoga With Adriene",
    "length": "24:37",
    "language": "EN",
    "style": "Calming flow",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Calming practice to balance the nervous system, morning or bedtime — premenstrual calm.",
    "url": "https://www.youtube.com/watch?v=Ba0fweKUwIc"
  },
  {
    "phase": "Late luteal (premenstrual)",
    "energy": "Low → Moderate",
    "intent": "Creative & inward (mood swings)",
    "title": "Yoga for Mood Swings",
    "channel": "Yoga With Adriene",
    "length": "23:45",
    "language": "EN",
    "style": "Healing flow",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Aimed at mood swings and balancing hormones and stress; soften and relax — premenstrual.",
    "url": "https://www.youtube.com/watch?v=K2LnW1gF6Eg"
  },
  {
    "phase": "Late luteal (premenstrual)",
    "energy": "Low → Moderate",
    "intent": "Creative & inward (stretch)",
    "title": "Yoga Stretch",
    "channel": "Yoga With Adriene",
    "length": "21:16",
    "language": "EN",
    "style": "Stretch",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Mindful stretch for when you're sore or a little anxious — lower-resistance late-luteal day.",
    "url": "https://www.youtube.com/watch?v=AF9d2Icl4fA"
  },
  {
    "phase": "Late luteal (premenstrual)",
    "energy": "Low → Moderate",
    "intent": "Creative & inward (anger)",
    "title": "Yoga For When You're Angry",
    "channel": "Yoga With Adriene",
    "length": "18:20",
    "language": "EN",
    "style": "Breath + asana + humor",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Built for anger and feeling misunderstood — the irritability the book lists for late luteal.",
    "url": "https://www.youtube.com/watch?v=ie5yjNGLxfQ"
  },
  {
    "phase": "Late luteal (premenstrual)",
    "energy": "Low → Moderate",
    "intent": "Creative & inward (headache)",
    "title": "Yoga For Hangovers",
    "channel": "Yoga With Adriene",
    "length": "22:26",
    "language": "EN",
    "style": "Gentle rejuvenating",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Gentle, nurturing practice for a throbbing head — premenstrual headache days.",
    "url": "https://www.youtube.com/watch?v=mkn07qa5SGA"
  },
  {
    "phase": "Late luteal (premenstrual)",
    "energy": "Low → Moderate",
    "intent": "Creative & inward (cool down)",
    "title": "Yoga For Runners 2 - Cool Down Sequence",
    "channel": "Yoga With Adriene",
    "length": "18:00",
    "language": "EN",
    "style": "Cool-down stretch",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Short post-run cool-down stretch — easy, low-resistance.",
    "url": "https://www.youtube.com/watch?v=nzCMptGGZt8"
  }
];
