export const videos = [
  {
    "phase": "Menstrual (bleeding)",
    "energy": "Low",
    "intent": "Rest & soothe (cramps, low back, nervous system)",
    "title": "Quick Restorative Yin Yoga – 20 Minute Practice",
    "channel": "Yoga With Adriene",
    "length": "≈20 min",
    "language": "EN",
    "style": "Restorative / Yin",
    "breathFocus": "High",
    "modifications": "Yes (props-friendly)",
    "notes": "Restorative pacing; great when you want minimal effort and maximum downshift.",
    "url": "https://www.youtube.com/watch?v=nylNjxeOeSw"
  },
  {
    "phase": "Menstrual (bleeding)",
    "energy": "Low",
    "intent": "Rest & soothe (PMS + cramps)",
    "title": "Yoga for Cramps and PMS | 20-Minute Home Yoga",
    "channel": "Yoga With Adriene",
    "length": "≈20 min",
    "language": "EN",
    "style": "Gentle / Restorative",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Designed for PMS/cramps; soft belly breathing cues.",
    "url": "https://www.youtube.com/watch?v=4JaCcp39iVI"
  },
  {
    "phase": "Menstrual (bleeding)",
    "energy": "Low",
    "intent": "Rest & soothe (stress relief)",
    "title": "20 minute Yin Yoga for Relaxation (Release Stress & CALM)",
    "channel": "SarahBethYoga",
    "length": "20 min",
    "language": "EN",
    "style": "Yin / Relaxation",
    "breathFocus": "High",
    "modifications": "Yes (all levels)",
    "notes": "Simple, calming shapes with longer holds; easy to modify.",
    "url": "https://www.youtube.com/watch?v=AFCRhcXYFm4"
  },
  {
    "phase": "Menstrual (bleeding)",
    "energy": "Low",
    "intent": "Rest & soothe (period support in Spanish)",
    "title": "YOGA para la MENSTRUACIÓN – alivia dolores, hinchazón y SPM (20 min)",
    "channel": "Boticaria Yoga",
    "length": "20 min",
    "language": "ES",
    "style": "Suave / Restaurativo",
    "breathFocus": "High",
    "modifications": "Yes (all levels)",
    "notes": "Period-focused; gentle/restorative approach with relaxation emphasis.",
    "url": "https://www.youtube.com/watch?v=WfIWo3eGtsE"
  },
  {
    "phase": "Early follicular (post-bleed)",
    "energy": "Low → Moderate",
    "intent": "Rebuild & mobilize (gentle wake-up)",
    "title": "Sunrise Yoga | 15 Min Morning Yoga Practice",
    "channel": "Yoga With Tim",
    "length": "15 min",
    "language": "EN",
    "style": "Morning flow",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "A clean, cue-forward wake-up flow—great for easing back into movement.",
    "url": "https://www.youtube.com/watch?v=lsV286HgxPU"
  },
  {
    "phase": "Early follicular (post-bleed)",
    "energy": "Low → Moderate",
    "intent": "Rebuild & mobilize (sweet release)",
    "title": "15 min Morning Yoga for Flexibility – Sweet Release SLOW FLOW",
    "channel": "Yoga with Kassandra",
    "length": "15 min",
    "language": "EN",
    "style": "Slow flow",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Slow-flow pacing with clear cueing; good for stiffness and gradual ramp-up.",
    "url": "https://www.youtube.com/watch?v=zLer5A9LgMs"
  },
  {
    "phase": "Early follicular (post-bleed)",
    "energy": "Low → Moderate",
    "intent": "Rebuild & mobilize (stress + flexibility)",
    "title": "Yoga to Heal Stress – 20 Minute Yoga Practice (Flexibility & Relaxation)",
    "channel": "Yoga With Adriene",
    "length": "≈20 min",
    "language": "EN",
    "style": "Gentle flow",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Breath-led, down-regulating practice with plenty of room to soften.",
    "url": "https://www.youtube.com/watch?v=tD_l3fDTFyg"
  },
  {
    "phase": "Early follicular (post-bleed)",
    "energy": "Low → Moderate",
    "intent": "Rebuild & mobilize (full body, Spanish)",
    "title": "Yoga at Home – Full Body Class | Vinyasa Yoga (20 min)",
    "channel": "MalovaElena",
    "length": "20 min",
    "language": "ES",
    "style": "Vinyasa",
    "breathFocus": "Med–High",
    "modifications": "Some options",
    "notes": "Spanish vinyasa with an alignment-forward approach (great for language + form).",
    "url": "https://www.youtube.com/watch?v=69G2udeeXPc"
  },
  {
    "phase": "Mid follicular (rising)",
    "energy": "Moderate",
    "intent": "Open & expand (stretch + strength)",
    "title": "20 min Morning Yoga Flow – Daily Stretch & Strength Routine",
    "channel": "Yoga with Kassandra",
    "length": "20 min",
    "language": "EN",
    "style": "Vinyasa flow",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Balanced flow that feels 'bright' without being too intense.",
    "url": "https://www.youtube.com/watch?v=EuAwhogdukQ"
  },
  {
    "phase": "Mid follicular (rising)",
    "energy": "Moderate",
    "intent": "Open & expand (move stuck energy)",
    "title": "Move that Energy! – a 20 Minute Yoga Class",
    "channel": "Five Parks Yoga",
    "length": "≈20 min",
    "language": "EN",
    "style": "Flow (mood boost)",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Great 'reset' flow—energizing but still mindful.",
    "url": "https://www.youtube.com/watch?v=AweT8J15UcY"
  },
  {
    "phase": "Mid follicular (rising)",
    "energy": "Moderate",
    "intent": "Open & expand (feel-good daily ritual)",
    "title": "20 Minute Everyday Yoga Flow | Daily Routine To Feel Your Best",
    "channel": "Charlie Follows",
    "length": "20 min",
    "language": "EN",
    "style": "Vinyasa (playful)",
    "breathFocus": "Med",
    "modifications": "Some options",
    "notes": "Creative transitions + upbeat vibe; choose when you want to feel 'in motion'.",
    "url": "https://www.youtube.com/watch?v=xE_pGjpycac"
  },
  {
    "phase": "Mid follicular (rising)",
    "energy": "Moderate",
    "intent": "Open & expand (Spanish flow)",
    "title": "Práctica de Flow para todo el cuerpo | 20 Min. de Yoga",
    "channel": "Yoga con Adriene en Español",
    "length": "20 min",
    "language": "ES",
    "style": "Flow",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Adriene-style cueing in Spanish (audio is auto-dubbed on some uploads).",
    "url": "https://www.youtube.com/watch?v=VwtspIZIktM"
  },
  {
    "phase": "Ovulation (peak)",
    "energy": "High",
    "intent": "Power & play (sweaty, strong)",
    "title": "15 MIN Morning Yoga Power Flow | Full Body Stretch & Workout",
    "channel": "Yoga With Tim",
    "length": "15 min",
    "language": "EN",
    "style": "Power vinyasa",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Short, strong, and sweaty—great when you want heat without a long practice.",
    "url": "https://www.youtube.com/watch?v=tq-vxTqoiHw"
  },
  {
    "phase": "Ovulation (peak)",
    "energy": "High",
    "intent": "Power & play (energizing full-body)",
    "title": "Try this 20 min Yoga Flow | Energising Full Body Routine",
    "channel": "Charlie Follows",
    "length": "20 min",
    "language": "EN",
    "style": "Energizing vinyasa",
    "breathFocus": "Med",
    "modifications": "Some options",
    "notes": "Dynamic sequence; ideal for 'I want to move!' days.",
    "url": "https://www.youtube.com/watch?v=k3ybhxZewLg"
  },
  {
    "phase": "Ovulation (peak)",
    "energy": "High",
    "intent": "Power & play (quick boost)",
    "title": "10 Minute Morning Yoga – Energy Boost Yoga",
    "channel": "Yoga with Kassandra",
    "length": "10 min",
    "language": "EN",
    "style": "Quick flow",
    "breathFocus": "Med",
    "modifications": "Yes",
    "notes": "Perfect when you're short on time but want a 'spark'.",
    "url": "https://www.youtube.com/watch?v=w8nPq-MtGOA"
  },
  {
    "phase": "Ovulation (peak)",
    "energy": "High",
    "intent": "Power & play (Spanish full-body flow)",
    "title": "YOGA FLOW PARA TODO CUERPO EN 20 MINUTOS",
    "channel": "MalovaElena",
    "length": "20 min",
    "language": "ES",
    "style": "Vinyasa",
    "breathFocus": "Med",
    "modifications": "Some options",
    "notes": "A solid Spanish flow option for energetic days.",
    "url": "https://www.youtube.com/watch?v=IM9uK5V77gM"
  },
  {
    "phase": "Early luteal (post-ovulation)",
    "energy": "Moderate",
    "intent": "Ground & strengthen (stability + power)",
    "title": "20 Min Yoga for Strength & Flexibility | Full Body Flow (All Levels)",
    "channel": "Yoga With Tim",
    "length": "20 min",
    "language": "EN",
    "style": "Strength flow",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Strong-but-steady: great for feeling capable and grounded.",
    "url": "https://www.youtube.com/watch?v=sZLSBMrEZwA"
  },
  {
    "phase": "Early luteal (post-ovulation)",
    "energy": "Moderate",
    "intent": "Ground & strengthen (steady daily flow)",
    "title": "20 minute Morning Yoga Flow ☀️ Every Day Full Body Yoga (All Levels)",
    "channel": "SarahBethYoga",
    "length": "20 min",
    "language": "EN",
    "style": "Morning flow",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Clear, no-fuss cueing; consistent pacing.",
    "url": "https://www.youtube.com/watch?v=a0GaOvCfjyE"
  },
  {
    "phase": "Early luteal (post-ovulation)",
    "energy": "Moderate",
    "intent": "Ground & strengthen (daily essentials)",
    "title": "20 Min Daily Yoga Flow | Every Day Full Body Yoga For All Levels",
    "channel": "Charlie Follows",
    "length": "20 min",
    "language": "EN",
    "style": "Steady vinyasa",
    "breathFocus": "Med",
    "modifications": "Some options",
    "notes": "A 'basics done well' flow to keep you consistent.",
    "url": "https://www.youtube.com/watch?v=sOjXETbN32g"
  },
  {
    "phase": "Early luteal (post-ovulation)",
    "energy": "Moderate",
    "intent": "Ground & strengthen (Spanish vinyasa)",
    "title": "YOGA PARA TODO CUERPO | VINYASA YOGA | YOGA EN CASA 20 MIN",
    "channel": "MalovaElena",
    "length": "20 min",
    "language": "ES",
    "style": "Vinyasa",
    "breathFocus": "Med",
    "modifications": "Some options",
    "notes": "Good 'daily practice' option in Spanish.",
    "url": "https://www.youtube.com/watch?v=PGaxPUsTZD4"
  },
  {
    "phase": "Mid luteal (settling)",
    "energy": "Moderate → Low",
    "intent": "Regulate & release (hips + low back)",
    "title": "20 Min Yoga For Hips & Lower Back Release | Deep Yoga Stretch",
    "channel": "Yoga With Tim",
    "length": "20 min",
    "language": "EN",
    "style": "Mobility / Deep stretch",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Excellent for bloating/back tension days—deep but controlled.",
    "url": "https://www.youtube.com/watch?v=IQe2RR_Bgzo"
  },
  {
    "phase": "Mid luteal (settling)",
    "energy": "Moderate → Low",
    "intent": "Regulate & release (anxiety reset)",
    "title": "Quick Escape – 20 Minute Yoga Class",
    "channel": "Five Parks Yoga",
    "length": "21:31",
    "language": "EN",
    "style": "Flow (nervous system reset)",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Specifically framed for anxiety/overwhelm—move + breathe to downshift.",
    "url": "https://www.youtube.com/watch?v=dFmx0xMsAgo"
  },
  {
    "phase": "Mid luteal (settling)",
    "energy": "Moderate → Low",
    "intent": "Regulate & release (feel-good + release tension)",
    "title": "20 Min Yoga to FEEL GOOD! (Beginner Friendly Yoga)",
    "channel": "Yoga With Bird",
    "length": "20 min",
    "language": "EN",
    "style": "Flow + stretch",
    "breathFocus": "Med–High",
    "modifications": "Yes",
    "notes": "Supportive, soothing tone; good when emotions are 'close to the surface'.",
    "url": "https://www.youtube.com/watch?v=chuR6NHXviU"
  },
  {
    "phase": "Mid luteal (settling)",
    "energy": "Moderate → Low",
    "intent": "Regulate & release (breath in Spanish)",
    "title": "20 minutos de yoga para calmar la ansiedad (Pranayama) – Xuan Lan",
    "channel": "Xuan Lan Yoga",
    "length": "≈20 min",
    "language": "ES",
    "style": "Pranayama (breathwork)",
    "breathFocus": "Very high",
    "modifications": "N/A (seated)",
    "notes": "Breath-only option for days you want calm without much movement.",
    "url": "https://www.youtube.com/watch?v=UPjochWx44w"
  },
  {
    "phase": "Late luteal (premenstrual)",
    "energy": "Low → Moderate",
    "intent": "Creative & inward (yin, introspection)",
    "title": "20 min Morning Yin Yoga – HIPS & HAMSTRINGS",
    "channel": "Yoga with Kassandra",
    "length": "20 min",
    "language": "EN",
    "style": "Yin",
    "breathFocus": "High",
    "modifications": "Yes (props helpful)",
    "notes": "Great for inward days—longer holds + breath awareness.",
    "url": "https://www.youtube.com/watch?v=KyHnpaQkFCI"
  },
  {
    "phase": "Late luteal (premenstrual)",
    "energy": "Low → Moderate",
    "intent": "Creative & inward (slow, soulful)",
    "title": "20 Minute // RELAXING YOGA FLOW // The Yogi Witch",
    "channel": "The Yogi Witch",
    "length": "20 min",
    "language": "EN",
    "style": "Relaxing flow",
    "breathFocus": "High",
    "modifications": "Yes (props suggested)",
    "notes": "A little mystical / seasonal energy; great for reflective mornings.",
    "url": "https://www.youtube.com/watch?v=YWD_09-gwiI"
  },
  {
    "phase": "Late luteal (premenstrual)",
    "energy": "Low",
    "intent": "Creative & inward (nervous system calm)",
    "title": "Unlock Instant Calm: 10 Min Breath-work for Anxiety Relief",
    "channel": "Breathwork video (YouTube)",
    "length": "10 min",
    "language": "EN",
    "style": "Breathwork / Pranayama",
    "breathFocus": "Very high",
    "modifications": "N/A (seated)",
    "notes": "Perfect on tender days when movement feels like 'too much'.",
    "url": "https://www.youtube.com/watch?v=4OwZfOeOrlY"
  },
  {
    "phase": "Late luteal (premenstrual)",
    "energy": "Low",
    "intent": "Creative & inward (Spanish: stress + fatigue)",
    "title": "Yoga Suave para Liberar Estrés, Tensión y Cansancio",
    "channel": "Luly Garza Yoga",
    "length": "25 min",
    "language": "ES",
    "style": "Yoga suave",
    "breathFocus": "High",
    "modifications": "Yes",
    "notes": "Spanish gentle practice for tired / inward days (great for language immersion).",
    "url": "https://www.youtube.com/watch?v=C7WnqEg5x3k"
  }
];
